apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: springboot-login-rolebinding
subjects:
  - kind: ServiceAccount
    name: springboot-login-sa
roleRef:
  kind: Role
  name: springboot-login-role
  apiGroup: rbac.authorization.k8s.io
